export var POST_TODO_REQUEST = "POST_TODO_REQUEST";
export var DELETE_TODO_REQUEST = "DELETE_TODO_REQUEST";
export var UPDATE_TODO_REQUEST = "UPDATE_TODO_REQUEST";
export var FETCH_TODO_LIST_REQUEST = "FETCH_TODO_LIST_REQUEST";
export var FETCH_TODO_LIST_SUCCESS = "FETCH_TODO_LIST_SUCCESS";
export var FETCH_TODO_LIST_FAIL = "FETCH_TODO_LIST_FAIL";
